name: Make zpkg CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          ref: ci-build
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      # System dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libtinfo5 rclone
          pip install jinja2 numpy

      # Tar dependancies
      - name: Download tar file dependencies
        run: |
          bash PandABlocks-rootfs/.github/scripts/tar-files.sh linux-only
          cd tar-files
          curl -o device-tree-xlnx-xilinx-v2020.2.tar.gz -L https://github.com/Xilinx/device-tree-xlnx/archive/refs/tags/xilinx-v2020.2.tar.gz

    
      # S3 bucket
      - name: Mount Vivado S3 bucket
        #run: |
        #  sudo mkdir -p /tools/Xilinx
        #  sudo chmod -R a+rw /tools
        #  sudo ls -l /tools
        #  echo ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}:${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }} > ~/.passwd-s3fs
        #  chmod 600 ~/.passwd-s3fs
        #  s3fs dls-controls-fpga-vivado /tools/Xilinx -o passwd_file=${HOME}/.passwd-s3fs -o url=https://s3.echo.stfc.ac.uk -o use_path_request_style -o ro        
        run: |
          sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }} ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

      #CONFIG files
      - name: Generate rootfs CONFIG files - zynq
        run: |
          mkdir build
          bash PandABlocks-rootfs/.github/scripts/config-file-pbrootfs.sh zynq
          bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh

      - name: Generate fpga CONFIG file
        run: |
          bash PandABlocks-fpga/.github/scripts/config-file-fpga.sh
          cat PandABlocks-fpga/CONFIG

      # Verification of files/file structure
      - name: List workspace files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls PandABlocks-fpga
          echo " "
          ls PandABlocks-rootfs
          echo " "
          ls rootfs
          echo " "
          ls /tools/Xilinx/Vivado/2020.2

      # Build
      - name: Build repository
        run: |
          cd PandABlocks-fpga
          make carrier_fpga
          make boot
        #  source /tools/Xilinx/Vivado/2020.2/settings64.sh && vivado -mode batch
        #  source /tools/Xilinx/Vivado/2020.2/settings64.sh && vivado -mode batch        
        # fusermount -u /tools/Xilinx



      # Verification of build files
      #- name: List build files
      #  run: ls build

      # Artifacts
      #- name: Upload deps and boot build files
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: build-files-${{ matrix.platform }}
      #    path: |
      #      build/deps-*.zip
      #      build/boot-*.zip

      # Release 
      #- name: Release
      #  uses: softprops/action-gh-release@v1
        # Only release when a tag is pushed
      #  if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #    files: |
      #      build/deps-*.zip
      #      build/boot-*.zip
      #    body_path: ${{ github.workflow }}/PandABlocks-rootfs/CHANGELOG.rst
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
