name: Make zpkg CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          ref: ci-build
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs
      
      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get install -y s3fs libtinfo5 rclone
      
      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: |
          sudo mkdir -p /tools/Xilinx
          echo ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}:${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }} > ~/.passwd-s3fs
          chmod 600 ~/.passwd-s3fs
          sudo s3fs dls-controls-fpga-vivado /tools/Xilinx -o passwd_file=${HOME}/.passwd-s3fs -o url=https://s3.echo.stfc.ac.uk -o use_path_request_style -o ro
        #run: sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }} ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

      # Tar dependancies
      - name: Download tar file dependencies
        run: sudo bash PandABlocks-rootfs/.github/scripts/tar-files.sh

      #CONFIG files
      - name: Generate rootfs CONFIG files - zynq
        run: |
          mkdir build
          sudo bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh zynq

      # Verification of files/file structure
      - name: List workspace files
        run: |
          ls ${{ github.workspace }}
          echo " "
          ls PandABlocks-fpga
          echo " "
          ls PandABlocks-rootfs
          echo " "
          ls rootfs
          echo " "
          ls tar-files
          echo " "
          ls /tools/Xilinx
          echo " "

      # Build
      #- name: Make zips
      #  run: |
      #    cd PandABlocks-rootfs
      #    make zips

      # Verification of build files
      #- name: List build files
      #  run: ls build

      # Artifacts
      #- name: Upload deps and boot build files
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: build-files-${{ matrix.platform }}
      #    path: |
      #      build/deps-*.zip
      #      build/boot-*.zip

      # Release 
      #- name: Release
      #  uses: softprops/action-gh-release@v1
        # Only release when a tag is pushed
      #  if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #    files: |
      #      build/deps-*.zip
      #      build/boot-*.zip
      #    body_path: ${{ github.workflow }}/PandABlocks-rootfs/CHANGELOG.rst
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
