name: Tests CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga
      
      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo pip install jinja2 numpy

      #CONFIG files
      - name: Generate rootfs CONFIG files - zynq
        run: |
          mkdir build
          sudo bash PandABlocks-fpga/.github/scripts/config-file-fpga.sh
          cat PandABlocks-fpga/CONFIG

      # Run Tests
      - name: Make tests
        run: |
          cd PandABlocks-fpga
          make python_tests
