name: Tests CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga
      
      - name: Set up Python2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install s3fs libtinfo5
          pip install jinja2 numpy --user

      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: |
          sudo mkdir -p /tools/Xilinx
          echo ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}:${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }} > ~/.passwd-s3fs
          chmod 600 ~/.passwd-s3fs
          sudo s3fs dls-controls-fpga-vivado /tools/Xilinx -o passwd_file=${HOME}/.passwd-s3fs -o url=https://s3.echo.stfc.ac.uk -o use_path_request_style -o ro
      
      #CONFIG files
      - name: Generate fpga CONFIG files
        run: |
          mkdir build
          sudo bash PandABlocks-fpga/.github/scripts/config-file-fpga.sh
          cat PandABlocks-fpga/CONFIG

      # Run Tests
      - name: Make tests
        run: |
          cd PandABlocks-fpga
          make python_tests
          make python_timing
