name: Tests CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-fpga
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install rclone libtinfo5
          pip install jinja2 numpy
      
      #CONFIG files
      - name: Generate fpga CONFIG files
        run: |
          mkdir build
          sudo bash PandABlocks-fpga/.github/scripts/config-file-fpga.sh
          cat PandABlocks-fpga/CONFIG

      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: |
          sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }} ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

      # Run Tests
      - name: Make python tests
        run: |
          cd PandABlocks-fpga
          make python_tests
          make python_timing
      
      - name: Make hdl_test
        run: |   
          cd PandABlocks-fpga
          make autogen
          make hdl_test